version: '3'
services: 
  consul:
    image: consul
    ports:
      - "5500:8500"
      - "5600:8600/tcp"
      - "5600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - C:\Users\Milos\Desktop\consul:/consul/data
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - consul
    environment:
      - DB=consul
      - DBPORT=8500
volumes:
  consul:
