#POST CONFIG
POST http://localhost:5000/config/
Content-Type: application/json

{
  "entries": {
    "test1": "test1",
    "test2": "test2",
    "version": "vv"
  }

}

### GET CONFIGS
GET http://localhost:5000/config/
Content-Type: application/json

### GET SINGLE CONFIG
GET http://localhost:5000/config/808764a5-9fe5-4c91-ac2b-abbe69a79fe1/vv
Content-Type: application/json

### GET SINGLE CONFIG NOT EXISTING
GET http://localhost:5000/config/testnotfound41234123/
Content-Type: application/json

### DELETE SINGLE CONFIG
DELETE http://localhost:5000/config/808764a5-9fe5-4c91-ac2b-abbe69a79fe1/vv
Content-Type: application/json
